"""Check that the release builder refuses every release it must not produce.

`scripts/build_release.py` is the one path in this repository that holds a private signing key, so
what it refuses matters more than what it does. Each case below violates one protected condition
and requires a refusal:

* a signing key inside this repository, or inside any other Git work tree;
* a wheel whose updater still carries the placeholders, or carries a different key;
* a wheel, a manifest or a package whose versions disagree;
* a `SOURCE_DATE_EPOCH` that is not the committer time of the revision being built, a dirty tree,
  and two builds of one revision that do not come out byte-identical;
* a release tree that lost, gained or altered a file, re-signed an older manifest with another key,
  or points an artifact away from the origin the loaders accept;
* private key material anywhere in the output, including inside the wheel.

The last group builds a real release end to end in a throwaway clone and then reproduces it from
the recorded source commit with no private key at all, which is the property a stranger relies on.

Every key here is an ephemeral P-256 key generated by the test and written only under pytest's
temporary directory. None of them is a release key, and none of them signs anything published.
"""

from __future__ import annotations

import hashlib
import importlib.util
import io
import json
import shutil
import subprocess
import sys
import zipfile
from pathlib import Path
from types import ModuleType

import pytest
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import ec

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
BUILDER = REPOSITORY_ROOT / "scripts" / "build_release.py"


def load_builder() -> ModuleType:
    """Import the builder from its path; it is a script, not a package module."""
    spec = importlib.util.spec_from_file_location("build_release", BUILDER)
    assert spec is not None and spec.loader is not None, f"{BUILDER} cannot be loaded"
    module = importlib.util.module_from_spec(spec)
    sys.modules["build_release"] = module
    spec.loader.exec_module(module)
    return module


builder = load_builder()


def write_key(directory: Path) -> tuple[Path, ec.EllipticCurvePrivateKey]:
    """Write a throwaway P-256 key under `directory` and return it with its path."""
    key = ec.generate_private_key(ec.SECP256R1())
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / "throwaway-release-signing.pem"
    path.write_bytes(
        key.private_bytes(
            serialization.Encoding.PEM,
            serialization.PrivateFormat.PKCS8,
            serialization.NoEncryption(),
        )
    )
    return path, key


def git(repository: Path, *arguments: str) -> str:
    """Run git in `repository` and return its output."""
    completed = subprocess.run(  # noqa: S603 - fixed argument list, no shell.
        ["git", "-C", str(repository), *arguments],  # noqa: S607 - git from PATH.
        capture_output=True,
        encoding="utf-8",
        check=True,
    )
    return completed.stdout.strip()


# --- where the key may live --------------------------------------------------------------------


def test_refuses_a_key_inside_this_repository(tmp_path: Path) -> None:
    """Refuse a key inside this repository before it is read."""
    inside = REPOSITORY_ROOT / "connector-release" / "never-a-key.pem"
    with pytest.raises(builder.ReleaseBuildError, match="inside a Git work tree"):
        builder.refuse_key_location(inside, repository=REPOSITORY_ROOT)


def test_refuses_a_key_inside_any_other_git_work_tree(tmp_path: Path) -> None:
    """Refuse a key inside any Git work tree, not only inside this one."""
    other = tmp_path / "some-other-repository"
    (other / ".git").mkdir(parents=True)
    with pytest.raises(builder.ReleaseBuildError, match="inside a Git work tree"):
        builder.refuse_key_location(other / "keys" / "release.pem", repository=REPOSITORY_ROOT)


def test_accepts_a_key_outside_every_work_tree(tmp_path: Path) -> None:
    """Accept a key outside every work tree, so the refusals above are specific."""
    path, _ = write_key(tmp_path / "custody")
    assert builder.refuse_key_location(path, repository=REPOSITORY_ROOT) == path.resolve()


def test_refuses_a_key_that_is_not_p256(tmp_path: Path) -> None:
    """Refuse any curve but P-256, the only one the loaders verify."""
    other = ec.generate_private_key(ec.SECP384R1())
    path = tmp_path / "custody" / "wrong-curve.pem"
    path.parent.mkdir()
    path.write_bytes(
        other.private_bytes(
            serialization.Encoding.PEM,
            serialization.PrivateFormat.PKCS8,
            serialization.NoEncryption(),
        )
    )
    with pytest.raises(builder.ReleaseBuildError, match="P-256"):
        builder.load_signing_key(path, repository=REPOSITORY_ROOT)


# --- the wheel ---------------------------------------------------------------------------------


def fake_wheel(directory: Path, version: str, updater: str, metadata_version: str | None = None):
    """Write a minimal wheel carrying an updater and a METADATA."""
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / f"agentnexus_sdk-{version}-py3-none-any.whl"
    with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("agentnexus_sdk/updater.py", updater)
        archive.writestr(
            f"agentnexus_sdk-{version}.dist-info/METADATA",
            "Metadata-Version: 2.4\nName: agentnexus-sdk\n"
            f"Version: {metadata_version or version}\n",
        )
    return path


def test_refuses_an_unstamped_updater(tmp_path: Path) -> None:
    """Refuse an updater still carrying the placeholders; it could verify nothing."""
    updater = (
        'X: Final = "REPLACE_RELEASE_PUBLIC_KEY_X"\nY: Final = "REPLACE_RELEASE_PUBLIC_KEY_Y"\n'
    )
    wheel = fake_wheel(tmp_path, "9.9.9", updater)
    with pytest.raises(builder.ReleaseBuildError, match="unstamped updater"):
        builder.verify_wheel(wheel, version="9.9.9", coordinates=("a" * 64, "b" * 64))


def test_refuses_an_updater_stamped_with_another_key(tmp_path: Path) -> None:
    """Refuse an updater stamped with another key; it would trust the wrong releases."""
    wheel = fake_wheel(tmp_path, "9.9.9", f'X = "{"c" * 64}"\nY = "{"d" * 64}"\n')
    with pytest.raises(builder.ReleaseBuildError, match="different key"):
        builder.verify_wheel(wheel, version="9.9.9", coordinates=("a" * 64, "b" * 64))


def test_refuses_a_wheel_named_for_another_version(tmp_path: Path) -> None:
    """Refuse a wheel whose filename names another version."""
    wheel = fake_wheel(tmp_path, "9.9.8", f'X = "{"a" * 64}"\nY = "{"b" * 64}"\n')
    with pytest.raises(builder.ReleaseBuildError, match="does not carry version"):
        builder.verify_wheel(wheel, version="9.9.9", coordinates=("a" * 64, "b" * 64))


def test_refuses_wheel_metadata_for_another_version(tmp_path: Path) -> None:
    """Refuse a wheel whose own METADATA declares another version."""
    wheel = fake_wheel(tmp_path, "9.9.9", f'X = "{"a" * 64}"\nY = "{"b" * 64}"\n', "9.9.8")
    with pytest.raises(builder.ReleaseBuildError, match="METADATA"):
        builder.verify_wheel(wheel, version="9.9.9", coordinates=("a" * 64, "b" * 64))


def test_accepts_a_wheel_stamped_with_this_key(tmp_path: Path) -> None:
    """Accept a correctly stamped wheel, so the refusals above are specific."""
    wheel = fake_wheel(tmp_path, "9.9.9", f'X = "{"a" * 64}"\nY = "{"b" * 64}"\n')
    builder.verify_wheel(wheel, version="9.9.9", coordinates=("a" * 64, "b" * 64))


def test_refuses_package_versions_that_disagree(tmp_path: Path) -> None:
    """Refuse pyproject.toml and version.py naming two versions."""
    source = tmp_path / "source"
    (source / "src" / "agentnexus_sdk").mkdir(parents=True)
    (source / "pyproject.toml").write_text('[project]\nversion = "0.6.3"\n', encoding="utf-8")
    (source / "src" / "agentnexus_sdk" / "version.py").write_text(
        '__version__: Final = "0.6.2"\n', encoding="utf-8"
    )
    with pytest.raises(builder.ReleaseBuildError, match="disagree"):
        builder.read_version(source)


def test_refuses_a_version_other_than_the_one_expected(tmp_path: Path) -> None:
    """Refuse a commit that builds a version other than the one the operator named."""
    source = tmp_path / "source"
    (source / "src" / "agentnexus_sdk").mkdir(parents=True)
    (source / "pyproject.toml").write_text('[project]\nversion = "0.6.3"\n', encoding="utf-8")
    (source / "src" / "agentnexus_sdk" / "version.py").write_text(
        '__version__: Final = "0.6.3"\n', encoding="utf-8"
    )
    assert builder.read_version(source) == "0.6.3"
    with pytest.raises(builder.ReleaseBuildError, match=r"expected 0\.6\.4"):
        builder.read_version(source, expected="0.6.4")


# --- reproducibility ---------------------------------------------------------------------------


def test_the_epoch_is_the_committer_time_of_the_revision() -> None:
    """Derive the epoch from the commit, which is what lets anybody rederive it."""
    head = git(REPOSITORY_ROOT, "rev-parse", "HEAD")
    expected = int(git(REPOSITORY_ROOT, "log", "-1", "--format=%ct", head))
    assert builder.resolve_epoch(REPOSITORY_ROOT, head, environ={}) == expected


def test_refuses_an_inherited_epoch_that_is_not_the_revision(tmp_path: Path) -> None:
    """Refuse an exported epoch that disagrees with the commit instead of replacing it."""
    head = git(REPOSITORY_ROOT, "rev-parse", "HEAD")
    expected = int(git(REPOSITORY_ROOT, "log", "-1", "--format=%ct", head))
    with pytest.raises(builder.ReleaseBuildError, match="SOURCE_DATE_EPOCH"):
        builder.resolve_epoch(
            REPOSITORY_ROOT, head, environ={"SOURCE_DATE_EPOCH": str(expected + 1)}
        )


def test_refuses_two_builds_that_differ() -> None:
    """Refuse two different builds of one commit as not reproducible."""
    with pytest.raises(builder.ReleaseBuildError, match="not reproducible"):
        builder.require_reproducible(b"PK first", b"PK second")


def test_normalising_a_wheel_removes_what_the_platform_wrote(tmp_path: Path) -> None:
    """Drop the file mode and made-by system a platform wrote into the zip."""

    def written(system: int, mode: int) -> bytes:
        """Write one wheel variant, normalise it and return its bytes."""
        buffer = io.BytesIO()
        with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as archive:
            info = zipfile.ZipInfo("agentnexus_sdk/__init__.py", date_time=(2026, 9, 23, 15, 0, 0))
            info.create_system = system
            info.external_attr = mode << 16
            info.compress_type = zipfile.ZIP_DEFLATED
            archive.writestr(info, b"print('same bytes')\n")
        path = tmp_path / f"{system}-{mode:o}.whl"
        path.write_bytes(buffer.getvalue())
        builder.normalise_wheel(path)
        return path.read_bytes()

    assert written(0, 0o100666) == written(3, 0o100644)


def test_normalising_a_wheel_removes_the_line_endings_windows_wrote(tmp_path: Path) -> None:
    """Fold the CRLF a Windows build writes into METADATA, and the RECORD line that pins it.

    Setuptools writes METADATA in text mode, so a Windows build carries CRLF there and only
    there. The RECORD that pins it has to follow, or the wheel no longer verifies on install.
    """

    def written(newline: bytes) -> bytes:
        """Write one wheel variant, normalise it and return its bytes."""
        metadata = newline.join([b"Metadata-Version: 2.4", b"Name: agentnexus-sdk", b""])
        digest = builder.record_digest(metadata)
        record = (
            f"agentnexus_sdk-9.9.9.dist-info/METADATA,{digest},{len(metadata)}\n"
            "agentnexus_sdk-9.9.9.dist-info/RECORD,,\n"
        ).encode()
        path = tmp_path / f"{len(newline)}.whl"
        with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as archive:
            archive.writestr("agentnexus_sdk-9.9.9.dist-info/METADATA", metadata)
            archive.writestr("agentnexus_sdk-9.9.9.dist-info/RECORD", record)
        builder.normalise_wheel(path)
        return path.read_bytes()

    normalised = written(b"\r\n")
    assert normalised == written(b"\n")
    with zipfile.ZipFile(io.BytesIO(normalised)) as archive:
        metadata = archive.read("agentnexus_sdk-9.9.9.dist-info/METADATA")
        record = archive.read("agentnexus_sdk-9.9.9.dist-info/RECORD").decode()
    assert b"\r" not in metadata
    assert builder.record_digest(metadata) in record


def test_refuses_a_dirty_tree(tmp_path: Path) -> None:
    """Refuse a tree with an untracked file; it is not its commit."""
    clone = tmp_path / "clone"
    git(tmp_path, "clone", "--quiet", "--no-hardlinks", str(REPOSITORY_ROOT), str(clone))
    (clone / "untracked.txt").write_text("not committed\n", encoding="utf-8")
    with pytest.raises(builder.ReleaseBuildError, match="uncommitted or untracked"):
        builder.require_clean_tree(clone)


# --- the release tree --------------------------------------------------------------------------


def test_private_material_is_found_in_a_file_and_inside_the_wheel(tmp_path: Path) -> None:
    """Find the private scalar in a file and key armour inside a wheel entry."""
    _, key = write_key(tmp_path / "custody")
    markers = builder.private_markers(key)
    tree = tmp_path / "tree"
    tree.mkdir()
    (tree / "notes.txt").write_text("nothing here\n", encoding="utf-8")
    assert builder.scan_private_material(tree, markers) == []

    scalar = format(key.private_numbers().private_value, "064x")
    (tree / "leak.txt").write_text(f"d={scalar}\n", encoding="utf-8")
    # Assembled at run time, so the tree-wide credential grep in CI does not find it here.
    armour = "-----BEGIN " + "PRIVATE KEY-----\n"
    with zipfile.ZipFile(tree / "leak.whl", "w") as archive:
        archive.writestr("agentnexus_sdk/leak.py", armour)
    found = builder.scan_private_material(tree, markers)
    assert any("leak.txt" in item for item in found)
    assert any("leak.whl" in item and "leak.py" in item for item in found)


# --- end to end --------------------------------------------------------------------------------


@pytest.fixture(scope="module")
def released(tmp_path_factory: pytest.TempPathFactory) -> dict[str, object]:
    """Build one real release, signed by a throwaway key, in a throwaway clone.

    The clone's committed release is re-stamped with that key first, so it plays the part of the
    previous release: the builder refuses a release signed by a key other than the one the
    published loaders carry, and a test release must not be the exception.
    """
    root = tmp_path_factory.mktemp("release")
    key_path, key = write_key(root / "custody")
    clone = root / "clone"
    git(root, "clone", "--quiet", "--no-hardlinks", str(REPOSITORY_ROOT), str(clone))
    git(clone, "config", "user.email", "test@example.invalid")
    git(clone, "config", "user.name", "Release builder test")
    git(clone, "config", "core.autocrlf", "false")

    x, y = builder.public_coordinates(key)
    release = clone / "connector-release"
    for name in builder.LOADERS:
        source = (clone / "installers" / name).read_text(encoding="utf-8")
        stamped = source.replace(builder.PLACEHOLDER_X, x).replace(builder.PLACEHOLDER_Y, y)
        (release / name).write_bytes(stamped.encode("utf-8"))
    manifest = (release / "connector" / "connector-release.json").read_bytes()
    (release / "connector" / "connector-release.json.sig").write_text(
        builder.sign(key, manifest).hex(), encoding="ascii"
    )
    git(clone, "add", "-A")
    git(clone, "commit", "--quiet", "-m", "test: the previous release, under a throwaway key")
    source_commit = git(clone, "rev-parse", "HEAD")
    version = builder.read_version(clone)

    status = builder.main(
        [
            "build",
            "--repository",
            str(clone),
            "--signing-key",
            str(key_path),
            "--expect-version",
            version,
            *(["--public-agent-endpoint-approved"] if builder.gate_is_open(clone) else []),
        ]
    )
    assert status == 0, "the builder refused a release it should have produced"
    return {
        "clone": clone,
        "key": key,
        "key_path": key_path,
        "version": version,
        "source_commit": source_commit,
        "coordinates": (x, y),
    }


def test_the_release_tree_is_the_previous_one_plus_one_wheel(released: dict[str, object]) -> None:
    """Change the manifest, its signature, one new wheel and the state record, and nothing else."""
    clone = released["clone"]
    assert isinstance(clone, Path)
    version = released["version"]
    changed = git(clone, "status", "--porcelain", "--untracked-files=all").splitlines()
    paths = sorted(line.split(maxsplit=1)[1] for line in changed)
    # The loaders are rewritten byte for byte from the same source and the same key, so they do not
    # show as changed: the release adds one wheel and moves the manifest, and nothing else.
    assert paths == sorted(
        [
            "connector-release/connector/connector-release.json",
            "connector-release/connector/connector-release.json.sig",
            f"connector-release/connector/{version}/agentnexus_sdk-{version}-py3-none-any.whl",
            "docs/releases/connector-release-state.json",
        ]
    ), paths


def test_the_manifest_names_the_wheel_on_the_loaders_origin(released: dict[str, object]) -> None:
    """Pin the new wheel's size and digest at the origin the loaders accept."""
    clone = released["clone"]
    assert isinstance(clone, Path)
    version = released["version"]
    release = clone / "connector-release"
    document = json.loads((release / "connector" / "connector-release.json").read_bytes())
    wheel = release / "connector" / str(version) / f"agentnexus_sdk-{version}-py3-none-any.whl"
    body = wheel.read_bytes()
    assert document["connector_version"] == version
    (artifact,) = document["artifacts"]
    assert artifact["url"] == (
        f"https://agntnexus.com/connector/{version}/agentnexus_sdk-{version}-py3-none-any.whl"
    )
    assert artifact["size"] == len(body)
    assert artifact["sha256"] == hashlib.sha256(body).hexdigest()


def test_the_state_records_where_the_release_came_from(released: dict[str, object]) -> None:
    """Record the source commit and its committer time in the state file."""
    clone = released["clone"]
    assert isinstance(clone, Path)
    state = json.loads((clone / builder.STATE_FILE).read_text(encoding="utf-8"))
    record = state["reproducible_releases"][released["version"]]
    assert record["source_commit"] == released["source_commit"]
    assert record["source_date_epoch"] == int(
        git(clone, "log", "-1", "--format=%ct", str(released["source_commit"]))
    )


def test_no_private_material_reached_the_tree(released: dict[str, object]) -> None:
    """Leave nothing derived from the private key anywhere in the written tree."""
    clone = released["clone"]
    key = released["key"]
    assert isinstance(clone, Path) and isinstance(key, ec.EllipticCurvePrivateKey)
    markers = builder.private_markers(key)
    assert builder.scan_private_material(clone / "connector-release", markers) == []


def committed(released: dict[str, object]) -> Path:
    """Commit the test release in its clone, once, and return the clone."""
    clone = released["clone"]
    assert isinstance(clone, Path)
    if git(clone, "status", "--porcelain"):
        git(clone, "add", "-A")
        git(clone, "commit", "--quiet", "-m", "release: the test release")
    return clone


def test_the_committed_release_reproduces_without_a_private_key(
    released: dict[str, object],
) -> None:
    """Rebuild the committed release byte for byte from its source with no key at all."""
    clone = committed(released)
    assert builder.main(["reproduce", "--repository", str(clone)]) == 0


def test_the_committed_release_passes_the_published_chain_check(
    released: dict[str, object],
) -> None:
    """Write what `ci/verify_release.py` accepts."""
    clone = committed(released)
    shutil.copy2(REPOSITORY_ROOT / "ci" / "verify_release.py", clone / "ci" / "verify_release.py")
    completed = subprocess.run(  # noqa: S603 - fixed argument list, no shell.
        [sys.executable, str(clone / "ci" / "verify_release.py")],
        capture_output=True,
        encoding="utf-8",
        check=False,
    )
    assert "signature  : verifies against the published key" in completed.stdout, completed.stderr
    assert "matches its declared digest and size" in completed.stdout, completed.stderr


@pytest.mark.parametrize(
    "mutation",
    [
        "drop-a-loader",
        "drop-an-older-wheel",
        "alter-an-older-wheel",
        "add-a-stray-file",
        "change-a-loader-line",
        "move-the-artifact-off-origin",
        "resign-with-another-key",
        "plant-a-private-key",
    ],
)
def test_a_damaged_release_tree_is_refused(
    released: dict[str, object], tmp_path: Path, mutation: str
) -> None:
    """Refuse each damage to a release tree on its own."""
    clone = committed(released)
    version = str(released["version"])
    tree = tmp_path / "tree"
    shutil.copytree(clone / "connector-release", tree)
    previous = tmp_path / "previous"
    builder.export_commit(clone, str(released["source_commit"]), previous)
    key = released["key"]
    assert isinstance(key, ec.EllipticCurvePrivateKey)

    older = sorted((tree / "connector").glob("0.1.0/*.whl"))[0]
    manifest_path = tree / "connector" / "connector-release.json"
    if mutation == "drop-a-loader":
        (tree / "remove.ps1").unlink()
    elif mutation == "drop-an-older-wheel":
        older.unlink()
    elif mutation == "alter-an-older-wheel":
        older.write_bytes(older.read_bytes() + b"\0")
    elif mutation == "add-a-stray-file":
        (tree / "connector" / "notes.txt").write_text("stray\n", encoding="utf-8")
    elif mutation == "change-a-loader-line":
        loader = tree / "connect.sh"
        loader.write_text(loader.read_text(encoding="utf-8") + "echo extra\n", encoding="utf-8")
    elif mutation == "move-the-artifact-off-origin":
        document = json.loads(manifest_path.read_bytes())
        document["artifacts"][0]["url"] = document["artifacts"][0]["url"].replace(
            "https://agntnexus.com", "https://example.invalid"
        )
        manifest_path.write_bytes(builder.canonical_bytes(document))
        (tree / "connector" / "connector-release.json.sig").write_text(
            builder.sign(key, manifest_path.read_bytes()).hex(), encoding="ascii"
        )
    elif mutation == "resign-with-another-key":
        other = ec.generate_private_key(ec.SECP256R1())
        ox, oy = builder.public_coordinates(other)
        for name in builder.LOADERS:
            source = (previous / "installers" / name).read_text(encoding="utf-8")
            stamped = source.replace(builder.PLACEHOLDER_X, ox).replace(builder.PLACEHOLDER_Y, oy)
            (tree / name).write_bytes(stamped.encode("utf-8"))
        (tree / "connector" / "connector-release.json.sig").write_text(
            builder.sign(other, manifest_path.read_bytes()).hex(), encoding="ascii"
        )
    elif mutation == "plant-a-private-key":
        (tree / "connector" / version / "release-signing.pem").write_bytes(
            key.private_bytes(
                serialization.Encoding.PEM,
                serialization.PrivateFormat.PKCS8,
                serialization.NoEncryption(),
            )
        )

    failures = builder.check_release_tree(
        tree,
        previous=previous / "connector-release",
        installers=previous / "installers",
        version=version,
        markers=builder.private_markers(key),
    )
    assert failures, f"{mutation} was not refused"


def test_reproduction_refuses_a_wheel_that_is_not_the_source(
    released: dict[str, object],
) -> None:
    """Refuse a committed wheel its source does not build; restoring it passes again."""
    clone = committed(released)
    version = str(released["version"])
    wheel = clone / "connector-release" / "connector" / version
    target = wheel / f"agentnexus_sdk-{version}-py3-none-any.whl"
    original = target.read_bytes()
    try:
        builder.normalise_wheel(target, extra={"agentnexus_sdk/extra.py": b"x = 1\n"})
        git(clone, "commit", "--quiet", "-am", "test: a wheel nobody built from source")
        assert builder.main(["reproduce", "--repository", str(clone)]) == 1
    finally:
        target.write_bytes(original)
        git(clone, "commit", "--quiet", "-am", "test: restore the built wheel")
    assert builder.main(["reproduce", "--repository", str(clone)]) == 0


def test_reproduction_refuses_a_version_with_no_recorded_source(tmp_path: Path) -> None:
    """Refuse to reproduce a post-legacy version with no recorded source commit."""
    clone = tmp_path / "clone"
    git(tmp_path, "clone", "--quiet", "--no-hardlinks", str(REPOSITORY_ROOT), str(clone))
    state_path = clone / builder.STATE_FILE
    state = json.loads(state_path.read_text(encoding="utf-8"))
    manifest = json.loads(
        (clone / "connector-release" / "connector" / "connector-release.json").read_bytes()
    )
    version = manifest["connector_version"]
    state.get("reproducible_releases", {}).pop(version, None)
    state_path.write_text(json.dumps(state, indent=2) + "\n", encoding="utf-8")
    if version in builder.LEGACY_RELEASES:
        assert builder.main(["reproduce", "--repository", str(clone)]) == 0
        manifest["connector_version"] = "9.9.9"
        path = clone / "connector-release" / "connector" / "connector-release.json"
        path.write_bytes(builder.canonical_bytes(manifest))
    assert builder.main(["reproduce", "--repository", str(clone)]) == 1


def test_the_builder_never_runs_in_ci() -> None:
    """Let CI reproduce a release but never build or sign one."""
    workflow = (REPOSITORY_ROOT / ".github" / "workflows" / "ci.yml").read_text(encoding="utf-8")
    assert "build_release.py build" not in workflow
    assert "--signing-key" not in workflow
    assert "secrets." not in workflow
